export const ADDED = 'todo/added'
export const TOGGLED = 'todo/toggled'
export const COLORSELECTD = 'todo/colorSelected'
export const DELETED = 'todo/deletd'
export const ALLCOMPLETED = 'todo/allCompleted'
export const CLEARCOMPLETED = 'todo/clearCompleted'